// ================== DATA ==================

const data = {

    ddl: [
        { query: "Create a table called STUDENT with columns: SID (NUMBER), SNAME (VARCHAR2(30)), AGE (NUMBER), COURSE (VARCHAR2(20))", img: "d1.png" },
        { query: "Create a table EMPLOYEE with columns: EID NUMBER, ENAME VARCHAR2(40), SALARY NUMBER(8,2), DEPTNO NUMBER", img: "d2.png" },
        { query: "Create a table DEPARTMENT with columns: DEPTNO NUMBER, DNAME VARCHAR2(30), LOCATION VARCHAR2(30)", img: "d3.png" },
        { query: "Create a table BOOK with columns: BOOK_ID NUMBER, TITLE VARCHAR2(50), AUTHOR VARCHAR2(40), PRICE NUMBER", img: "d4.png" },
        { query: "Create a table COURSE with columns: CID NUMBER, CNAME VARCHAR2(40), DURATION NUMBER", img: "d5.png" },
        { query: "Create a table PROJECT with columns: PID NUMBER, PNAME VARCHAR2(50), START_DATE DATE, END_DATE DATE", img: "d6.png" },
        { query: "Create a table CUSTOMER with columns: CID NUMBER, CNAME VARCHAR2(40), CITY VARCHAR2(30), PHONE NUMBER", img: "d7.png" },
        { query: "Create a table SALES with columns: SALE_ID NUMBER, PRODUCT_NAME VARCHAR2(50), QUANTITY NUMBER, PRICE NUMBER", img: "d8.png" },
        { query: "Create a table EMP_COPY from existing EMP table (structure only)", img: "d9.png" },
        { query: "Create a table EMP_BACKUP from EMP including data", img: "d10.png" },

        { query: "Add a column EMAIL VARCHAR2(50) to the STUDENT table", img: "d11.png" },
        { query: "Add a column PHONE NUMBER to the EMPLOYEE table", img: "d12.png" },
        { query: "Modify the column SNAME in STUDENT table to VARCHAR2(50)", img: "d13.png" },
        { query: "Modify the column SALARY in EMPLOYEE table to NUMBER(10,2)", img: "d14.png" },
        { query: "Add CITY and PINCODE columns to CUSTOMER table", img: "d15.png" },
        { query: "Rename column SNAME to STUDENT_NAME in STUDENT table", img: "d16.png" },
        { query: "Drop column AGE from STUDENT table", img: "d17.png" },
        { query: "Set SALARY column in EMPLOYEE table to NOT NULL", img: "d18.png" },
        { query: "Increase TITLE column size in BOOK table to VARCHAR2(100)", img: "d19.png" },
        { query: "Add column MANAGER_ID NUMBER to EMPLOYEE table", img: "d20.png" },

        { query: "Drop table STUDENT", img: "d21.png" },
        { query: "Drop table CUSTOMER", img: "d22.png" },
        { query: "Drop table PROJECT permanently", img: "d23.png" },
        { query: "Remove table SALES", img: "d24.png" },
        { query: "Drop table COURSE", img: "d25.png" },
        { query: "Rename table STUDENT to STUDENTS", img: "d26.png" },
        { query: "Rename table EMPLOYEE to EMP_MASTER", img: "d27.png" },
        { query: "Rename table CUSTOMER to CLIENT", img: "d28.png" },
        { query: "Rename table BOOK to BOOK_DETAILS", img: "d29.png" },
        { query: "Rename table PROJECT to PROJECT_INFO", img: "d30.png" },

        { query: "Remove all records from STUDENT table", img: "d31.png" },
        { query: "Truncate EMPLOYEE table", img: "d32.png" },
        { query: "Empty CUSTOMER table", img: "d33.png" },
        { query: "Remove all data from SALES table but keep structure", img: "d34.png" },
        { query: "Clear PROJECT table", img: "d35.png" },
        { query: "Create TRAINING table with TID, TNAME, DURATION", img: "d36.png" },
        { query: "Add TRAINER_NAME column to TRAINING", img: "d37.png" },
        { query: "Modify TNAME size to VARCHAR2(60)", img: "d38.png" },
        { query: "Rename TRAINING to TRAINING_PROGRAM", img: "d39.png" },
        { query: "Truncate TRAINING_PROGRAM table", img: "d40.png" },
        { query: "Drop TRAINING_PROGRAM table", img: "d41.png" },

        { query: "Create EMP_PROJECT table and later modify ROLE size and add STATUS", img: "d42.png" },
        { query: "Create PRODUCT table then rename column and modify datatype", img: "d43.png" },
        { query: "Create ORDERS table then add, drop and re-add TOTAL_AMOUNT", img: "d44.png" },
        { query: "Create EMP_TEMP then rename, truncate and drop", img: "d45.png" },
        { query: "Create STUDENT_RECORD then add, modify and rename columns", img: "d46.png" },
        { query: "Create EMP_ARCHIVE then add column and rename", img: "d47.png" },
        { query: "Create DEPT_BACKUP then drop and add column", img: "d48.png" },
        { query: "Create SALES_DATA then modify and rename table", img: "d49.png" },
        { query: "Create LOG_TABLE then truncate, rename and drop", img: "d50.png" }
    ],
dml: [
{ query: "Insert a record into STUDENT table with SID = 101, SNAME = 'RAHUL', AGE = 20, COURSE = 'MCA'", img: "m1.png" },
{ query: "Insert a record into EMPLOYEE table with EID = 201, ENAME = 'ANITA', SALARY = 45000, DEPTNO = 10", img: "m2.png" },
{ query: "Insert a new department into DEPT table with DEPTNO = 50, DNAME = 'TRAINING', LOC = 'DELHI'", img: "m3.png" },
{ query: "Insert a record into BOOK table with only BOOK_ID, TITLE, and PRICE", img: "m4.png" },
{ query: "Insert multiple rows into COURSE table", img: "m5.png" },
{ query: "Insert data into EMP_COPY table from EMP table", img: "m6.png" },
{ query: "Insert employees with salary > 3000 into EMP_HIGH_SAL", img: "m7.png" },
{ query: "Insert employees hired after 1981 into EMP_NEW_HIRE", img: "m8.png" },
{ query: "Insert DEPTNO and DNAME from DEPT into DEPT_BACKUP", img: "m9.png" },
{ query: "Insert employee names and salaries into EMP_SALARY_RECORD", img: "m10.png" },

{ query: "Update salary of employee SMITH to 2000", img: "m11.png" },
{ query: "Increase salary of all employees by 10%", img: "m12.png" },
{ query: "Update department number of employee ALLEN to 20", img: "m13.png" },
{ query: "Update commission of SALESMAN to 500", img: "m14.png" },
{ query: "Update job of employee MILLER to MANAGER", img: "m15.png" },
{ query: "Increase salary of employees in department 10 by 20%", img: "m16.png" },
{ query: "Update salary of employees whose job is CLERK to 1500", img: "m17.png" },
{ query: "Update location of department 30 to MUMBAI", img: "m18.png" },
{ query: "Update commission of employees with NULL commission to 100", img: "m19.png" },
{ query: "Update salary of employees who earn less than average salary", img: "m20.png" },

{ query: "Delete employee SMITH from EMP table", img: "m21.png" },
{ query: "Delete all employees in department 30", img: "m22.png" },
{ query: "Delete employees with salary less than 1000", img: "m23.png" },
{ query: "Delete employees hired before 1981", img: "m24.png" },
{ query: "Delete employees who do not receive commission", img: "m25.png" },
{ query: "Delete departments located in CHICAGO", img: "m26.png" },
{ query: "Delete employees whose job is CLERK", img: "m27.png" },
{ query: "Delete employees earning minimum salary", img: "m28.png" },
{ query: "Delete employees working in departments in NEW YORK", img: "m29.png" },
{ query: "Delete employees whose manager number is NULL", img: "m30.png" }
],
dql: [
{ query: "Display all columns of the EMP table.", img: "s1.png" },

{ query: "Display EMPNO, ENAME, and SAL of all employees from the EMP table.", img: "s2.png" },

{ query: "Display unique job titles from the EMP table.", img: "s3.png" },

{ query: "Display employee names along with their department numbers from the EMP table.", img: "s4.png" },

{ query: "Display all department details from the DEPT table.", img: "s5.png" },

{ query: "Display distinct department numbers from the EMP table.", img: "s6.png" },

{ query: "Display employee name and annual salary from the EMP table.", img: "s7.png" },

{ query: "Display employee name, salary, and commission from the EMP table.", img: "s8.png" },

{ query: "Display job and salary of all employees from the EMP table.", img: "s9.png" },

{ query: "Display employees along with their manager numbers from the EMP table.", img: "s10.png" }
],
where: [
{ query: "Display employees whose salary is greater than 3000.", img: "w1.png" },
{ query: "Display employees working in department 10.", img: "w2.png" },
{ query: "Display employees whose job is 'CLERK'.", img: "w3.png" },
{ query: "Display employees hired after 01-JAN-81.", img: "w4.png" },
{ query: "Display employees whose salary is less than 1500.", img: "w5.png" },
{ query: "Display employees whose salary is > 2000 and job is 'MANAGER'.", img: "w6.png" },
{ query: "Display employees working in department 10 or 20.", img: "w7.png" },
{ query: "Display employees whose job is 'SALESMAN' and salary > 1500.", img: "w8.png" },
{ query: "Display employees who are either CLERK or ANALYST.", img: "w9.png" },
{ query: "Display employees hired before 1982 and working in department 30.", img: "w10.png" },

{ query: "Display employees working in departments 10, 20, or 30.", img: "w11.png" },
{ query: "Display employees whose job is not MANAGER or CLERK.", img: "w12.png" },
{ query: "Display employees whose department is not 10.", img: "w13.png" },
{ query: "Display employees whose salary is between 1000 and 3000.", img: "w14.png" },
{ query: "Display employees hired between 01-JAN-81 and 31-DEC-81.", img: "w15.png" },
{ query: "Display all employees ordered by salary in ascending order.", img: "w16.png" },
{ query: "Display all employees ordered by salary in descending order.", img: "w17.png" },
{ query: "Display employees ordered by hire date.", img: "w18.png" },
{ query: "Display employees ordered by department number and salary.", img: "w19.png" },
{ query: "Display employees ordered by job (ascending) and salary (descending).", img: "w20.png" },

{ query: "Display employee names ordered alphabetically.", img: "w21.png" },
{ query: "Display employees of department 30 ordered by salary.", img: "w22.png" },
{ query: "Display employees ordered by annual salary.", img: "w23.png" },
{ query: "Display employees ordered by commission.", img: "w24.png" },
{ query: "Display employees ordered by job and name.", img: "w25.png" },
{ query: "Display employee name as Employee_Name.", img: "w26.png" },
{ query: "Display salary as Monthly_Salary.", img: "w27.png" },
{ query: "Display employee name and job with aliases.", img: "w28.png" },
{ query: "Display department number as Dept_No.", img: "w29.png" },
{ query: "Display employee name and salary with meaningful aliases.", img: "w30.png" },

{ query: "Display commission as Incentive.", img: "w31.png" },
{ query: "Display employee name, job, and salary with aliases, ordered by job.", img: "w32.png" },
{ query: "Display employees of department 30 whose salary > 1500, ordered by salary.", img: "w33.png" },
{ query: "Display employees whose commission is NOT NULL, ordered by commission.", img: "w34.png" },
{ query: "Display employees whose salary is between 1500 and 3000, ordered by salary.", img: "w35.png" },
{ query: "Display employee name and department, ordered by department and name.", img: "w36.png" },
{ query: "Display employees whose name starts with 'S', ordered by salary.", img: "w37.png" },
{ query: "Display employees hired before 1982 with aliases, ordered by hire date.", img: "w38.png" },
{ query: "Display employee name as Name and salary as Pay for department 10.", img: "w39.png" },
{ query: "Display employees whose commission is NULL, ordered by salary descending.", img: "w40.png" },

{ query: "Display employee name and annual salary, ordered by annual salary.", img: "w41.png" },
{ query: "Display employees whose commission is NULL but job is SALESMAN.", img: "w42.png" },
{ query: "Display employees whose manager is NULL and salary > 4000.", img: "w43.png" },
{ query: "Display employees who do not earn commission and work in department 20.", img: "w44.png" },
{ query: "Display employees whose commission is NOT NULL and department is 30.", img: "w45.png" },
{ query: "Display employees whose commission is NULL or salary > 3000.", img: "w46.png" },
{ query: "Display employees whose commission is NULL and salary > 2000.", img: "w47.png" },
{ query: "Display employees whose manager is not NULL.", img: "w48.png" },
{ query: "Display employees who do not have a manager.", img: "w49.png" },
{ query: "Display employees who are getting commission.", img: "w50.png" },

{ query: "Display employees whose commission is NULL.", img: "w51.png" },
{ query: "Display job and salary using aliases.", img: "w52.png" },
{ query: "Display employee name and department number with aliases.", img: "w53.png" },
{ query: "Display hire date as Joining_Date.", img: "w54.png" }
],
pttrn: [
{ query: "Display employees whose name starts with A.", img: "l1.png" },
{ query: "Display employees whose name starts with S.", img: "l2.png" },
{ query: "Display employees whose name ends with N.", img: "l3.png" },
{ query: "Display employees whose name ends with R.", img: "l4.png" },
{ query: "Display employees whose name contains LL.", img: "l5.png" },
{ query: "Display employees whose name contains AR.", img: "l6.png" },
{ query: "Display employees whose job starts with M.", img: "l7.png" },
{ query: "Display employees whose job ends with AN.", img: "l8.png" },
{ query: "Display employees whose job contains CL.", img: "l9.png" },
{ query: "Display departments whose location starts with N.", img: "l10.png" },

{ query: "Display employees whose name has exactly 4 characters.", img: "l11.png" },
{ query: "Display employees whose name has exactly 5 characters.", img: "l12.png" },
{ query: "Display employees whose name has A as the second character.", img: "l13.png" },
{ query: "Display employees whose name has L as the third character.", img: "l14.png" },
{ query: "Display employees whose job has exactly 6 characters.", img: "l15.png" },
{ query: "Display employees whose name starts with any letter but ends with N.", img: "l16.png" },
{ query: "Display employees whose job starts with any one character and ends with ER.", img: "l17.png" },
{ query: "Display employees whose name has A as the first and N as the last character.", img: "l18.png" },
{ query: "Display employees whose name has exactly 2 characters before 'E'.", img: "l19.png" },
{ query: "Display employees whose name has exactly 1 character after 'A'.", img: "l20.png" },

{ query: "Display employees whose name starts with A and ends with N.", img: "l21.png" },
{ query: "Display employees whose name contains E anywhere.", img: "l22.png" },
{ query: "Display employees whose name does not contain A.", img: "l23.png" },
{ query: "Display employees whose job contains MAN.", img: "l24.png" },
{ query: "Display employees whose job does not start with C.", img: "l25.png" },
{ query: "Display employees whose name contains two L consecutively.", img: "l26.png" },
{ query: "Display employees whose name starts with J and has S anywhere.", img: "l27.png" },
{ query: "Display employees whose job starts with S and ends with AN.", img: "l28.png" },
{ query: "Display employees whose name contains A as the second last character.", img: "l29.png" },
{ query: "Display employees whose name contains exactly one character between A and E.", img: "l30.png" },

{ query: "Display employees whose name starts with S and salary > 2000.", img: "l31.png" },
{ query: "Display employees whose job ends with MAN and department is 20.", img: "l32.png" },
{ query: "Display employees whose name contains A and commission is NULL.", img: "l33.png" },
{ query: "Display employees whose job starts with C and salary < 1500.", img: "l34.png" },
{ query: "Display employees whose name ends with S and hired after 1981.", img: "l35.png" },
{ query: "Display employees whose name starts with M and department is not 10.", img: "l36.png" },
{ query: "Display employees whose job contains ER and salary between 2000 and 3000.", img: "l37.png" },
{ query: "Display employees whose name starts with A or job starts with S.", img: "l38.png" },
{ query: "Display employees whose name contains I and manager is NOT NULL.", img: "l39.png" },
{ query: "Display employees whose name ends with N and commission is NOT NULL.", img: "l40.png" },

{ query: "Display employee name as Name whose name starts with S, ordered alphabetically.", img: "l41.png" },
{ query: "Display employee name and salary as Pay whose name contains A, ordered by salary.", img: "l42.png" },
{ query: "Display employees whose job starts with M, ordered by job and salary.", img: "l43.png" },
{ query: "Display employees whose name ends with E, ordered by hire date.", img: "l44.png" },
{ query: "Display employee name and annual salary for employees whose name starts with J.", img: "l45.png" },
{ query: "Display employees whose name contains R, ordered by department number.", img: "l46.png" },
{ query: "Display employee name as Employee whose job ends with AN.", img: "l47.png" },
{ query: "Display employees whose name starts with K, ordered by salary descending.", img: "l48.png" },
{ query: "Display employees whose name contains L, ordered by name and salary.", img: "l49.png" },
{ query: "Display employees whose job starts with C, ordered by job.", img: "l50.png" },

{ query: "Display employees whose name has exactly 6 characters and ends with R.", img: "l51.png" },
{ query: "Display employees whose name has A as the third character from start.", img: "l52.png" },
{ query: "Display employees whose name has E as the second character from end.", img: "l53.png" },
{ query: "Display employees whose name contains at least two characters before 'A'.", img: "l54.png" },
{ query: "Display employees whose job contains exactly one 'A'.", img: "l55.png" },
{ query: "Display employees whose name does not start with a vowel.", img: "l56.png" },
{ query: "Display employees whose job does not contain ER.", img: "l57.png" },
{ query: "Display employees whose name starts and ends with the same character.", img: "l58.png" },
{ query: "Display employees whose name contains A and E in any order.", img: "l59.png" },
{ query: "Display employees whose name contains A but not as the first character.", img: "l60.png" }
],
grp: [
{ query: "Display the total number of employees.", img: "g1.png" },
{ query: "Display the total salary of all employees.", img: "g2.png" },
{ query: "Display the average salary of all employees.", img: "g3.png" },
{ query: "Display the highest salary.", img: "g4.png" },
{ query: "Display the lowest salary.", img: "g5.png" },
{ query: "Display the total number of departments in EMP table.", img: "g6.png" },
{ query: "Display the number of employees who are managers.", img: "g7.png" },
{ query: "Display the total commission paid to employees.", img: "g8.png" },
{ query: "Display the average commission.", img: "g9.png" },
{ query: "Display the number of employees who are getting commission.", img: "g10.png" },

{ query: "Display department-wise total salary.", img: "g11.png" },
{ query: "Display department-wise average salary.", img: "g12.png" },
{ query: "Display department-wise number of employees.", img: "g13.png" },
{ query: "Display job-wise number of employees.", img: "g14.png" },
{ query: "Display job-wise total salary.", img: "g15.png" },
{ query: "Display job-wise maximum salary.", img: "g16.png" },
{ query: "Display job-wise minimum salary.", img: "g17.png" },
{ query: "Display department-wise maximum salary.", img: "g18.png" },
{ query: "Display department-wise minimum salary.", img: "g19.png" },
{ query: "Display department-wise average commission.", img: "g20.png" },

{ query: "Display department-wise job-wise number of employees.", img: "g21.png" },
{ query: "Display department-wise job-wise total salary.", img: "g22.png" },
{ query: "Display department-wise job-wise average salary.", img: "g23.png" },
{ query: "Display job-wise department-wise maximum salary.", img: "g24.png" },
{ query: "Display job-wise department-wise minimum salary.", img: "g25.png" },
{ query: "Display department and job having highest total salary.", img: "g26.png" },
{ query: "Display department where sum of salaries is maximum.", img: "g27.png" },
{ query: "Display job having minimum average salary.", img: "g28.png" },
{ query: "Display jobs having average salary greater than department-wise average salary.", img: "g29.png" },
{ query: "Display department having highest number of employees.", img: "g30.png" },
],
subqueries: [
{ query: "Display employees whose salary is greater than JONES.", img: "a1.png" },
{ query: "Display employees earning the same salary as SCOTT.", img: "a2.png" },
{ query: "Display employees hired after ALLEN.", img: "a3.png" },
{ query: "Display employees working in the same department as BLAKE.", img: "a4.png" },
{ query: "Display employees having the same job as MILLER.", img: "a5.png" },
{ query: "Display employees earning less than the average salary.", img: "a6.png" },
{ query: "Display employees earning more than the maximum salary of CLERKs.", img: "a7.png" },
{ query: "Display employee(s) with the minimum salary.", img: "a8.png" },
{ query: "Display employee(s) with the maximum salary.", img: "a9.png" },
{ query: "Display employees working in departments located in NEW YORK.", img: "a10.png" },

{ query: "Display employees whose salary matches any salary in department 30.", img: "a11.png" },
{ query: "Display employees earning more than all CLERKs.", img: "a12.png" },
{ query: "Display employees earning less than any MANAGER.", img: "a13.png" },
{ query: "Display employees whose job appears in department 20.", img: "a14.png" },
{ query: "Display employees whose department has at least one SALESMAN.", img: "a15.png" },
{ query: "Display employees earning the same salary as any CLERK.", img: "a16.png" },
{ query: "Display employees who are not working in departments of SALESMAN.", img: "a17.png" },
{ query: "Display employees earning more than all employees in department 10.", img: "a18.png" },
{ query: "Display employees whose department number is among departments with more than 3 employees.", img: "a19.png" },
{ query: "Display employees whose salary is greater than salary of their manager.", img: "a20.png" },

{ query: "Display jobs where average salary is greater than overall average salary.", img: "a21.png" },
{ query: "Display employees earning more than the department average salary.", img: "a22.png" },
{ query: "Display employees earning the highest salary in each department.", img: "a23.png" },
{ query: "Display employees earning the lowest salary in each job.", img: "a24.png" },
{ query: "Display departments having total salary greater than department 20.", img: "a25.png" },
{ query: "Display employees whose salary equals the maximum salary of their job.", img: "a26.png" },
{ query: "Display employees earning more than the overall average salary.", img: "a27.png" },
{ query: "Display department(s) having the maximum number of employees.", img: "a28.png" },
{ query: "Display jobs having minimum average salary.", img: "a29.png" },
{ query: "Display employees earning more than the average salary of CLERKs.", img: "a30.png" },


],
scalar: [
{ query: "Display employee name, hire date, and current date. Also calculate the number of days the employee has worked.", img: "sf1.png" },
{ query: "Display employee name and hire date in the format: Monday, January 01, 2024.", img: "sf2.png" },
{ query: "Find employees who joined in the same month as the current system date (ignore year).", img: "sf3.png" },
{ query: "Display employee name and the next Monday after their hire date.", img: "sf4.png" },
{ query: "Display employee name and the last day of their joining month.", img: "sf5.png" },
{ query: "Find employees who have completed more than 10 years in the company.", img: "sf6.png" },
{ query: "Display employee name and number of months worked in the company.", img: "sf7.png" },
{ query: "Display employee name, hire date, and hire date after adding 3 years and 6 months.", img: "sf8.png" },
{ query: "Find employees hired between two given dates (use TO_DATE).", img: "sf9.png" },
{ query: "Display the difference in years between SYSDATE and hire date (rounded).", img: "sf10.png" },

{ query: "Display employee name and salary rounded to the nearest 1000.", img: "sf11.png" },
{ query: "Display salary truncated to 2 decimal places.", img: "sf12.png" },
{ query: "Display employee name and square root of salary.", img: "sf13.png" },
{ query: "Find the absolute difference between salary and 5000.", img: "sf14.png" },
{ query: "Display salary rounded up to the nearest integer.", img: "sf15.png" },
{ query: "Display salary rounded down to the nearest integer.", img: "sf16.png" },
{ query: "Generate a random number between 1 and 500 for each employee.", img: "sf17.png" },
{ query: "Display remainder when salary is divided by 2000.", img: "sf18.png" },
{ query: "Display salary raised to the power of 3.", img: "sf19.png" },
{ query: "Round salary to nearest hundred and thousand (two columns).", img: "sf20.png" },

{ query: "Display employee names in uppercase and lowercase in two columns.", img: "sf21.png" },
{ query: "Display employee name and its length.", img: "sf22.png" },
{ query: "Display first 4 characters of employee name.", img: "sf23.png" },
{ query: "Concatenate employee name and job using - symbol.", img: "sf24.png" },
{ query: "Replace all occurrences of letter ‘A’ with ‘#’ in employee names.", img: "sf25.png" },
{ query: "Display position of first occurrence of ‘E’ in employee name.", img: "sf26.png" },
],
joins: [
{ query: "Display employee name and department name.", img: "j1.png" },
{ query: "Display employee name, salary, and department location.", img: "j2.png" },
{ query: "Display employee name and department name for department 10.", img: "j3.png" },
{ query: "Display employee name and department name where salary > 2000.", img: "j4.png" },
{ query: "Display employee name, job, and department name.", img: "j5.png" },
{ query: "Display employee name and department location for CLERKs.", img: "j6.png" },
{ query: "Display employee name and department name working in NEW YORK.", img: "j7.png" },
{ query: "Display employee name, department number, and department name.", img: "j8.png" },
{ query: "Display employees hired after 1981 with department name.", img: "j9.png" },
{ query: "Display employees with commission along with department name.", img: "j10.png" },

{ query: "Display employees whose salary is between 1500 and 3000 with department.", img: "j11.png" },
{ query: "Display employees who are the only employee in their department.", img: "j12.png" },
{ query: "Display employees whose department has more than 3 employees.", img: "j13.png" },
{ query: "Display departments where no employee earns more than 2000.", img: "j14.png" },
{ query: "Display employees who earn more than at least one manager.", img: "j15.png" },
{ query: "Display employees who share same job and department.", img: "j16.png" },
{ query: "Display employees working in same department as their manager.", img: "j17.png" },
{ query: "Display employees whose manager works in a different department.", img: "j18.png" },
{ query: "Display employees who are highest paid in their department.", img: "j19.png" },
{ query: "Display employees earning more than their department average.", img: "j20.png" },

{ query: "Display department with maximum employees.", img: "j21.png" },
{ query: "Display department with highest total salary.", img: "j22.png" },
{ query: "Display department name and average salary.", img: "j23.png" },
{ query: "Display department name and total salary.", img: "j24.png" },
],
set: [
{ query: "Display all department numbers from both EMP and DEPT tables using UNION.", img: "u1.png" },
{ query: "Display all department numbers from EMP and DEPT including duplicates using UNION ALL.", img: "u2.png" },
{ query: "Display department numbers that are present in both EMP and DEPT using INTERSECT.", img: "u3.png" },
{ query: "Display department numbers that are present in EMP but not in DEPT using MINUS.", img: "u4.png" },
{ query: "Display department numbers that are present in DEPT but not assigned to any employee.", img: "u5.png" },

{ query: "Display employee names and department names in a single column using UNION.", img: "u6.png" },
{ query: "Display all employee names and department names, including duplicates.", img: "u7.png" },
{ query: "Display jobs that exist in EMP table and also exist as department names in DEPT table.", img: "u8.png" },
{ query: "Display employee names that are not department names.", img: "u9.png" },
{ query: "Display department locations that are not used by any employee.", img: "u10.png" },

],
views: [
{ query: "Create a view to display employee name, salary, and department number from EMP table.", img: "v1.png" },
{ query: "Create a view to display employee name and department name by joining EMP and DEPT tables.", img: "v2.png" },
{ query: "Create a view to display employees working in department 10.", img: "v3.png" },
{ query: "Create a view to display employee name, job, and annual salary (SAL * 12).", img: "v4.png" },
{ query: "Create a view to display department name and location from DEPT table.", img: "v5.png" },

{ query: "Create a view to display employee name, department name, and location.", img: "v6.png" },
{ query: "Create a view to display employees earning more than 3000.", img: "v7.png" },
{ query: "Create a view to display department-wise total salary using EMP table.", img: "v8.png" },
{ query: "Create a view to display only managers (JOB = 'MANAGER').", img: "v9.png" },
{ query: "Create a view with column aliases for employee name and salary.", img: "v10.png" },
],
tcl: [
{ query: "Grant SELECT privilege on EMP table to a user named USER1.", img: "tcl1.png" },
{ query: "Grant SELECT and INSERT privileges on EMP table to USER2.", img: "tcl2.png" },
{ query: "Grant all privileges on DEPT table to USER3.", img: "tcl3.png" },
{ query: "Grant SELECT privilege on EMP table to USER4 with GRANT OPTION.", img: "tcl4.png" },
{ query: "Grant UPDATE privilege only on SAL column of EMP table to USER5.", img: "tcl5.png" },

{ query: "Grant DELETE privilege on EMP table to USER6.", img: "tcl6.png" },
{ query: "Grant SELECT privilege on both EMP and DEPT tables to USER7.", img: "tcl7.png" },
{ query: "Grant privileges on EMP table to PUBLIC.", img: "tcl8.png" },
{ query: "Grant INSERT privilege on EMP table to USER8 with GRANT OPTION.", img: "tcl9.png" },
{ query: "Grant UPDATE and DELETE privileges on EMP table to USER9.", img: "tcl10.png" },

{ query: "Revoke SELECT privilege on EMP table from USER1.", img: "tcl11.png" },
{ query: "Revoke INSERT and UPDATE privileges on EMP table from USER2.", img: "tcl12.png" },
{ query: "Revoke ALL privileges on DEPT table from USER3.", img: "tcl13.png" },
{ query: "Revoke GRANT OPTION from USER4 on EMP table.", img: "tcl14.png" },
{ query: "Revoke UPDATE privilege on SAL column from USER5.", img: "tcl15.png" },

{ query: "Revoke DELETE privilege on EMP table from USER6.", img: "tcl16.png" },
{ query: "Revoke privileges granted to PUBLIC on EMP table.", img: "tcl17.png" },
{ query: "Revoke all privileges on EMP table from USER9.", img: "tcl18.png" },
{ query: "Insert a new employee record into EMP table and commit the changes.", img: "tcl19.png" },
{ query: "Update salary of employees in department 10 and commit the changes.", img: "tcl20.png" },
],
output: [
{ query: "Write a PL/SQL block to print your name and city in two separate lines.", img: "z1.png" },
{ query: "Write a PL/SQL block to display numbers from 1 to 5 using DBMS_OUTPUT.PUT_LINE.", img: "z2.png" },
{ query: "Write a PL/SQL block to print the current system date.", img: "z3.png" },
{ query: "Write a PL/SQL block to display employee name and salary using variables.", img: "z4.png" },
{ query: "Write a PL/SQL block to declare a variable and assign your age, then display it.", img: "z5.png" },

{ query: "Write a PL/SQL block to declare two variables and print their sum.", img: "z6.png" },
{ query: "Write a PL/SQL block to store employee name and salary in variables and display them.", img: "z7.png" },
{ query: "Write a PL/SQL block to swap two numbers using variables.", img: "z8.png" },
{ query: "Write a PL/SQL block to calculate area of a rectangle using variables.", img: "z9.png" },
{ query: "Write a PL/SQL block to declare a constant value for PI and calculate area of a circle.", img: "z10.png" },

{ query: "Write a PL/SQL block to declare a constant tax rate and calculate total salary after tax.", img: "z11.png" },
{ query: "Write a PL/SQL block where constant value cannot be changed.", img: "z12.png" },
{ query: "Write a PL/SQL block to calculate simple interest using constant rate of interest.", img: "z13.png" },
{ query: "Write a PL/SQL block using different datatypes: NUMBER, VARCHAR2, DATE.", img: "z14.png" },
{ query: "Write a PL/SQL block to declare a variable using %TYPE from EMP table salary column.", img: "z15.png" },

{ query: "Write a PL/SQL block to declare a record using %ROWTYPE and display employee details.", img: "z16.png" },
{ query: "Write a PL/SQL block to store and display current date using DATE datatype.", img: "z17.png" },
{ query: "Write a PL/SQL block to convert number to string and display it.", img: "z18.png" },
{ query: "Write a PL/SQL block using variables, constants, and output statement together.", img: "z19.png" },
{ query: "Write a PL/SQL block to display employee details using %ROWTYPE, constants, and comments.", img: "z20.png" },

{ query: "Write a PL/SQL block to calculate bonus (10% of salary) and display result using proper comments.", img: "z21.png" },
{ query: "Write a PL/SQL block that uses all concepts: variable, constant, datatype, and output.", img: "z22.png" }
],
dc: [
{ query: "Write a PL/SQL block to check if a number is positive.", img: "dc1.png" },
{ query: "Write a PL/SQL block to check if an employee’s salary is greater than 3000.", img: "dc2.png" },
{ query: "Write a PL/SQL block to check if a given number is even.", img: "dc3.png" },
{ query: "Write a PL/SQL block to display a message if today is Monday.", img: "dc4.png" },
{ query: "Write a PL/SQL block to check if a number is divisible by 5.", img: "dc5.png" },

{ query: "Write a PL/SQL block to check whether a number is even or odd.", img: "dc6.png" },
{ query: "Write a PL/SQL block to check whether a number is positive or negative.", img: "dc7.png" },
{ query: "Write a PL/SQL block to compare two numbers and display the greater one.", img: "dc8.png" },
{ query: "Write a PL/SQL block to check whether a student passed (marks ≥ 40) or failed.", img: "dc9.png" },
{ query: "Write a PL/SQL block to check if salary is above average (use fixed value).", img: "dc10.png" },

{ query: "Write a PL/SQL block to assign grades based on marks (≥80 A, ≥60 B, ≥40 C, else Fail).", img: "dc11.png" },
{ query: "Write a PL/SQL block to find the greatest of three numbers.", img: "dc12.png" },
{ query: "Write a PL/SQL block to check if a number is Positive, Negative, or Zero.", img: "dc13.png" },
{ query: "Write a PL/SQL block to categorize salary (High >5000, Medium 3000–5000, Low <3000).", img: "dc14.png" },
{ query: "Write a PL/SQL block to calculate bonus based on job role.", img: "dc15.png" },

{ query: "Write a PL/SQL block using CASE to display day of week based on number (1–7).", img: "dc16.png" },
{ query: "Write a PL/SQL block using CASE to assign grades based on marks.", img: "dc17.png" },
{ query: "Write a PL/SQL block using CASE to check whether a number is even or odd.", img: "dc18.png" },
{ query: "Write a PL/SQL block using CASE to display department name based on department id.", img: "dc19.png" },
{ query: "Write a PL/SQL block using CASE to categorize salary (High/Medium/Low).", img: "dc20.png" },
],
ic: [
{ query: "Write a PL/SQL block to print numbers from 1 to 5 using SIMPLE LOOP.", img: "ic1.png" },
{ query: "Write a PL/SQL block to display numbers from 10 to 1 in reverse order.", img: "ic2.png" },
{ query: "Write a PL/SQL block to calculate the sum of numbers from 1 to 10.", img: "ic3.png" },
{ query: "Write a PL/SQL block to print multiplication table of a number using SIMPLE LOOP.", img: "ic4.png" },
{ query: "Write a PL/SQL block to print even numbers between 1 and 20.", img: "ic5.png" },

{ query: "Write a PL/SQL block that exits the loop when a number becomes greater than 50.", img: "ic6.png" },
{ query: "Write a PL/SQL block to print numbers from 1 to 10 using WHILE LOOP.", img: "ic7.png" },
{ query: "Write a PL/SQL block to calculate factorial of a number using WHILE LOOP.", img: "ic8.png" },
{ query: "Write a PL/SQL block to display sum of digits of a number using WHILE LOOP.", img: "ic9.png" },
{ query: "Write a PL/SQL block to reverse a number using WHILE LOOP.", img: "ic10.png" },

{ query: "Write a PL/SQL block to check whether a number is palindrome using WHILE LOOP.", img: "ic11.png" },
{ query: "Write a PL/SQL block to print Fibonacci series up to N terms using WHILE LOOP.", img: "ic12.png" },
{ query: "Write a PL/SQL block to print numbers from 1 to 10 using FOR LOOP.", img: "ic13.png" },
{ query: "Write a PL/SQL block to print numbers in reverse order using FOR LOOP.", img: "ic14.png" },
{ query: "Write a PL/SQL block to calculate sum of first 10 natural numbers using FOR LOOP.", img: "ic15.png" },

{ query: "Write a PL/SQL block to display multiplication table of 5 using FOR LOOP.", img: "ic16.png" },
{ query: "Write a PL/SQL block to print squares of numbers from 1 to 10.", img: "ic17.png" },
{ query: "Write a PL/SQL block to display all odd numbers between 1 and 50.", img: "ic18.png" },
{ query: "Write a PL/SQL block to print a pattern using nested loops.", img: "ic19.png" },
{ query: "Write a PL/SQL block to print multiplication tables from 1 to 5.", img: "ic20.png" },
],
type: [
{ query: "Write a PL/SQL block to fetch employee name from EMP table for empno = 7369 and display it.", img: "rw1.png" },
{ query: "Write a PL/SQL block to retrieve salary of an employee and print it.", img: "rw2.png" },
{ query: "Write a PL/SQL block to fetch employee name and job using a single SELECT statement.", img: "rw3.png" },
{ query: "Write a PL/SQL block to display department number of an employee using SELECT INTO.", img: "rw4.png" },
{ query: "Write a PL/SQL block to fetch hiredate of an employee and display it.", img: "rw5.png" },

{ query: "Write a PL/SQL block to count total number of employees using SELECT INTO.", img: "rw6.png" },
{ query: "Write a PL/SQL block to declare a variable using %TYPE based on EMP.SAL and display salary.", img: "rw7.png" },
{ query: "Write a PL/SQL block to declare variables for employee name and job using %TYPE.", img: "rw8.png" },
{ query: "Write a PL/SQL block to fetch salary using %TYPE variable and display it.", img: "rw9.png" },
{ query: "Write a PL/SQL block to calculate annual salary using %TYPE variable.", img: "rw10.png" },

{ query: "Write a PL/SQL block to update salary using %TYPE variable.", img: "rw11.png" },
{ query: "Write a PL/SQL block to declare a variable using %TYPE from DEPT table.", img: "rw12.png" },
{ query: "Write a PL/SQL block to declare a record using %ROWTYPE for EMP table.", img: "rw13.png" },
{ query: "Write a PL/SQL block to fetch complete employee record using %ROWTYPE and display fields.", img: "rw14.png" },
{ query: "Write a PL/SQL block to display employee name, salary, and job using %ROWTYPE.", img: "rw15.png" },
{ query: "Write a PL/SQL block to update salary using %ROWTYPE variable.", img: "rw16.png" },
{ query: "Write a PL/SQL block to insert a record using %ROWTYPE.", img: "rw17.png" },
],
cursor: [
{ query: "Write a PL/SQL block to declare a cursor to fetch all employees from EMP table and display their names.", img: "cu1.png" },
{ query: "Write a PL/SQL block to fetch employee name and salary using cursor and display them.", img: "cu2.png" },
{ query: "Write a PL/SQL block to display employees whose salary is greater than 3000 using cursor.", img: "cu3.png" },
{ query: "Write a PL/SQL block to count number of employees using cursor.", img: "cu4.png" },
{ query: "Write a PL/SQL block to calculate total salary of all employees using cursor.", img: "cu5.png" },
{ query: "Write a PL/SQL block to fetch records one by one using OPEN, FETCH, and CLOSE.", img: "cu6.png" },
{ query: "Write a PL/SQL block to display all employee records using cursor FOR LOOP.", img: "cu7.png" },
{ query: "Write a PL/SQL block to display employee names and jobs using cursor FOR LOOP.", img: "cu8.png" },
{ query: "Write a PL/SQL block to display employees from department 10 using cursor FOR LOOP.", img: "cu9.png" },
{ query: "Write a PL/SQL block to calculate total salary using cursor FOR LOOP.", img: "cu10.png" },
{ query: "Write a PL/SQL block to display employees with salary greater than average using cursor FOR LOOP.", img: "cu11.png" },
{ query: "Write a PL/SQL block to declare a parameterized cursor that takes department number and displays employees of that department.", img: "cu12.png" },
{ query: "Write a PL/SQL block to fetch employees whose salary is greater than a given value using parameterized cursor.", img: "cu13.png" },
{ query: "Write a PL/SQL block to display employees based on job role using parameterized cursor.", img: "cu14.png" },
{ query: "Write a PL/SQL block to calculate total salary of a given department using parameterized cursor.", img: "cu15.png" },
{ query: "Write a PL/SQL block to pass multiple parameters (deptno, job) to cursor and display matching records.", img: "cu16.png" },
{ query: "Write a PL/SQL block to update salary of employees using cursor with FOR UPDATE.", img: "cu17.png" },
{ query: "Write a PL/SQL block to increase salary by 10% for employees using WHERE CURRENT OF.", img: "cu18.png" },
{ query: "Write a PL/SQL block to delete employees with salary less than 2000 using cursor.", img: "cu19.png" },
{ query: "Write a PL/SQL block to update job of employees using updatable cursor.", img: "cu20.png" },
],
stored: [
{ query: "Write a stored procedure to display 'Hello Oracle' using DBMS_OUTPUT.", img: "pro1.png" },
{ query: "Write a stored procedure to display employee name for a given empno.", img: "pro2.png" },
{ query: "Write a stored procedure to print salary of an employee.", img: "pro3.png" },
{ query: "Write a stored procedure to display all employees using cursor.", img: "pro4.png" },
{ query: "Write a stored procedure to display department details.", img: "pro5.png" },
{ query: "Write a stored procedure that takes empno as input and displays employee details.", img: "pro6.png" },
{ query: "Write a stored procedure that takes department number and displays employees of that department.", img: "pro7.png" },
{ query: "Write a stored procedure that takes salary as input and displays employees earning more than that.", img: "pro8.png" },
{ query: "Write a stored procedure with OUT parameter to return employee salary.", img: "pro9.png" },
{ query: "Write a stored procedure with IN OUT parameter to update salary and return new salary.", img: "pro10.png" },
],
package: [
{ query: "Write a package specification and body to display 'Hello Oracle'.", img: "pac1.png" },
{ query: "Create a package with one procedure to display employee details.", img: "pac2.png" },
{ query: "Create a package containing a function to return square of a number.", img: "pac3.png" },
{ query: "Write a package with both procedure and function.", img: "pac4.png" },
{ query: "Create a package to group employee-related operations.", img: "pac5.png" },
{ query: "Create a package with a global variable and display its value.", img: "pac6.png" },
{ query: "Write a package to store company name as constant and display it.", img: "pac7.png" },
{ query: "Create a package that uses a variable to count number of procedure calls.", img: "pac8.png" },
{ query: "Write a package with a global variable used in multiple procedures.", img: "pac9.png" },
{ query: "Create a package procedure to fetch employee details using empno.", img: "pac10.png" },
],
ehandling: [
{ query: "Write a PL/SQL block to handle NO_DATA_FOUND exception while fetching employee details.", img: "eh1.png" },
{ query: "Write a PL/SQL block to handle TOO_MANY_ROWS exception.", img: "eh2.png" },
{ query: "Write a PL/SQL block to handle ZERO_DIVIDE exception.", img: "eh3.png" },
{ query: "Write a PL/SQL block to handle VALUE_ERROR exception.", img: "eh4.png" },
{ query: "Write a PL/SQL block with a generic WHEN OTHERS exception handler.", img: "eh5.png" },

{ query: "Write a PL/SQL block to display error code and message using SQLCODE and SQLERRM.", img: "eh6.png" },
{ query: "Write a PL/SQL block to capture and display error details when division by zero occurs.", img: "eh7.png" },
{ query: "Write a PL/SQL block to log exception message into a variable and display it.", img: "eh8.png" },
{ query: "Write a PL/SQL block to raise an error if salary is less than 2000 using RAISE_APPLICATION_ERROR.", img: "eh9.png" },
{ query: "Write a PL/SQL block to validate employee age and raise custom error if age < 18.", img: "eh10.png" },

{ query: "Write a PL/SQL block to restrict update operation using RAISE_APPLICATION_ERROR.", img: "eh11.png" },
{ query: "Write a PL/SQL block to raise an error when invalid department number is entered.", img: "eh12.png" },
{ query: "Write a PL/SQL block to declare and handle a user-defined exception.", img: "eh13.png" },
{ query: "Write a PL/SQL block to raise a custom exception when salary exceeds limit.", img: "eh14.png" },
{ query: "Write a PL/SQL block to validate input and raise user-defined exception for invalid data.", img: "eh15.png" },

{ query: "Write a PL/SQL block to handle multiple user-defined exceptions.", img: "eh16.png" },
{ query: "Write a PL/SQL block to catch an exception and re-raise it using RAISE.", img: "eh17.png" },
{ query: "Write a PL/SQL block where exception is handled in inner block and re-raised to outer block.", img: "eh18.png" },
{ query: "Write a PL/SQL block to log error and then re-raise it.", img: "eh19.png" },
{ query: "Write a PL/SQL block to fetch employee details and handle all possible exceptions.", img: "eh20.png" },
],
triggers: [
{ query: "Write a trigger to display a message whenever a record is inserted into EMP table.", img: "tr1.png" },
{ query: "Write a trigger that fires before inserting data into EMP table.", img: "tr2.png" },
{ query: "Write a trigger that fires after deleting a record from EMP table.", img: "tr3.png" },
{ query: "Write a trigger to prevent deletion from EMP table.", img: "tr4.png" },
{ query: "Write a trigger to display a message when employee salary is updated.", img: "tr5.png" },
{ query: "Write a row-level trigger to display old and new salary when salary is updated.", img: "tr6.png" },
{ query: "Write a trigger to restrict salary update if new salary is less than old salary.", img: "tr7.png" },
{ query: "Write a trigger to automatically set hiredate while inserting employee record.", img: "tr8.png" },
{ query: "Write a trigger to increase salary by 5% before updating.", img: "tr9.png" },
{ query: "Write a trigger to copy deleted records into another table (audit table).", img: "tr10.png" },
{ query: "Write a statement-level trigger to display message when any insert occurs on EMP table.", img: "tr11.png" },
{ query: "Write a statement-level trigger to log update operations on EMP table.", img: "tr12.png" },
{ query: "Write a trigger that fires once for DELETE statement regardless of number of rows.", img: "tr13.png" },
{ query: "Write a BEFORE trigger to validate salary before inserting.", img: "tr14.png" },
{ query: "Write an AFTER trigger to log inserted employee records.", img: "tr15.png" },
{ query: "Write both BEFORE and AFTER triggers for UPDATE operation.", img: "tr16.png" },
{ query: "Write a trigger that fires only when salary > 5000.", img: "tr17.png" },
{ query: "Write a trigger to allow insert only during working hours.", img: "tr18.png" },
{ query: "Write a trigger to prevent update on weekends.", img: "tr19.png" },
{ query: "Write a trigger to maintain audit table for INSERT, UPDATE, DELETE.", img: "tr20.png" },
]
};


function showSection(section) {
    let content = document.getElementById("content");

    let topicData = data[section];

    if (!topicData) {
        content.innerHTML = "<p>No data available for this section</p>";
        return;
    }

    let html = `<h2>${section.toUpperCase()} Queries</h2>`;

    topicData.forEach((item, index) => {
        html += `
        <div class="question-box">
            <h2>Question ${index + 1}</h2>

            <p><b>Query:</b></p>
            <pre>${item.query}</pre>

            <p><b>Output:</b></p>
            <img src="images/${item.img}" alt="Output">
        </div>
        `;
    });

    content.innerHTML = html;
}